### ISSUE TITLE
Random question

### ISSUE THREAD

**Issue by leshow** [sile/patricia_tree#11]
I've looked at this code a bunch and always wondered, what's up with these two conditions. Do you happen to remember? Apologies for the sort of weird ask:

```
    pub(crate) fn insert(&mut self, key: &[u8], value: V) -> Option<V> {
        if self.label().get(0) > key.get(0) {
```

This condition also shows up a bunch:
```
} else if common_prefix_len == 0 && self.label().get(0) <= key.get(0) {
```

I don't understand why it would matter that the first byte is `<=`, or conversely on insertion why it would matter if the label being added starts with a larger byte. Any insight?

The condition on `insert` makes it such that if you have `"abc"` and insert `"dabc"` you get `"dabc" - sibling -> "abc"` instead of the other way around, but I'm not sure why that matters.

**Comment by sile** [comment]
Thank you for your question.
Since I'm busy on weekdays, I'll respond weekend.

**Comment by sile** [comment]
> The condition on `insert` makes it such that if you have `"abc"` and insert `"dabc"` you get `"dabc" - sibling -> "abc"`

It's not true.
Since `self.label() == "abc"` and `key == "dabc"`, the condition becomes `'a' > 'd'`. 
Thus it doesn't hold and we get `"abc" - sibling -> "dabc"` I think.

**Comment by sile** [comment]
(BTW, looking back the code I think that I might be able to use `<` instead of `<=` in the condition `self.label().get(0) <= key.get(0)`.)
