### ISSUE TITLE
Expose the return type of PatriciaMap::common_prefixes as a concrete type

### ISSUE THREAD

**Issue by alexkirsz** [sile/patricia_tree#16]
The return type of `PatriciaMap::common_prefixes` is `impl 'b + Iterator<Item = (&'b [u8], &'a V)>`. This causes issues when you need to compose it in your own iterator--for instance, if you build your own data structure on top of a `PatriciaMap`. Instead, you will either have to `Box` the iterator, or use the `type_alias_impl_trait` unstable feature.

It would be better from the perspective of a user of your API is `PatriciaMap::common_prefixes` returned a `CommonPrefixesIter<'a, 'b, V>`.

**Comment by sile** [comment]
Sounds good. Thank you for proposing this idea.
As I don't have enough time to fix this crate for a while, it's very welcome to create a PR addressing this issue if you're interested.
