### ISSUE TITLE
Get longest common prefix

### ISSUE THREAD

**Issue by Eliot00** [sile/patricia_tree#38]
I want to segment a long string

Expect:

```rust
use patricia_tree::PatriciaMap;

let mut map = PatriciaMap::new();
map.insert("foo", 1);
map.insert("foobar", 2);
assert_eq!(map.get_longest_common_prefix("fo"), "fo");
assert_eq!(map.get_longest_common_prefix("fobaz"), "fo");
```

Current:

```rust
use patricia_tree::PatriciaMap;

let mut map = PatriciaMap::new();
map.insert("foo", 1);
map.insert("foobar", 2);
assert_eq!(map.get_longest_common_prefix("fo"), None);
assert_eq!(map.get_longest_common_prefix("fobaz"), None);
assert_eq!(map.get_longest_common_prefix("foo"), Some(("foo".as_bytes(), &1)));
assert_eq!(map.get_longest_common_prefix("fooba"), Some(("foo".as_bytes(), &1)));
assert_eq!(map.get_longest_common_prefix("foobar"), Some(("foobar".as_bytes(), &2)));
assert_eq!(map.get_longest_common_prefix("foobarbaz"), Some(("foobar".as_bytes(), &2)));
```

**Comment by sile** [comment]
Thank you for creating this issue.
Unfortunately, I'm busy this week. I will see the detail and reply several days later.

**Comment by sile** [comment]
Hi, I saw the issue detail.

The method name (`get_longest_common_prefix()`) may lead to misunderstandings, but the method description and example suggest, the current behaviour is the intended one. 

I think that we need to implement a new method to archive the behaviour you want to do.
(If you are interested in implementing this method, your contribution would be welcomed.)

**Comment by Eliot00** [comment]
Thank you for taking the time to review my issue report and provide clarification. I want to contribute but I'm still a rust newbie.

Please don't feel any obligation, but if you happen to have some bandwidth to implement this, many users would find it useful.

**Comment by sile** [comment]
It's acceptable to implement the method, but could you please explain its use case?
(I would like to know whether this method is truly helpful for users.)

**Comment by Eliot00** [comment]
I hope to use `patricia_tree` in an input method program to store a Chinese character encoding dictionary (because Chinese characters cannot be input directly with the keyboard), for example, "ni" means "你" and "hao" means "好". The user will not always enter the complete encoding, when the user only enters "nih", I hope to be able to split it into ["ni", "h"], and then I can query the encoding of the two words separately and output these two words.

I hope my explanation can make sense to you.

**Comment by sile** [comment]
I see. Thank you for your explanation!
