### ISSUE TITLE
Is it safe to share a read only PatriciaMap across multiple thread?

### ISSUE THREAD

**Issue by 12101111** [sile/patricia_tree#9]
In another word, is it safe to add `unsafe impl<V> Sync for Node<V> {}` ?

**Comment by sile** [comment]
I'm not 100% sure but it seems okay to implement `Sync` for `Node<V>`.

**Comment by leshow** [comment]
You need to implement it like,

```
unsafe impl<V: Sync> Sync for Node<V> {}
unsafe impl<V: Send> Send for Node<V> {}
```

 which is something I got wrong initially

**Comment by sile** [comment]
@leshow You're right. Thank you for your advice!
